name: Deploy Infrastructure and Application

on:
  push:
    branches: [ main ]
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/deploy.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      # ✅ SECURITY SCAN: Static Analysis using Trivy for IaC misconfigurations
      - name: Security Scan (Trivy IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          exit-code: 0
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          format: table

      - name: Terraform Init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform init -reconfigure

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve tfplan

      - name: Simulate Artifact
        run: |
          echo "Hello from GitHub Actions" > artifact.txt
          zip app.zip artifact.txt

      # ✅ Get S3 bucket name from Terraform output
      - name: Get Terraform Output (S3 Bucket)
        id: get_bucket
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          BUCKET_NAME=$(terraform output -raw static_assets_bucket_name)
          echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV

      # ✅ Upload to S3 using dynamic bucket name
      - name: Upload Artifact to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: ${{ env.BUCKET_NAME }}
        run: |
          echo "Uploading to bucket: $BUCKET_NAME"
          aws s3 cp app.zip s3://$BUCKET_NAME/
